### ISSUE TITLE
Sourcemaps unhelpful with {compress: true} option

### ISSUE THREAD

**Issue by ghost** [davidrekow/less-stream#1]
If you pass the `{compress: true}` option to less combined with gulp-sourcemaps, it inserts two sourcemaps into the final file. The first maps styles to the original *.less file (helpful), and the second maps everything to line 1 of the compressed file (not helpful). Unfortunately, the second map is what you see when you inspect elements in the browser. If you manually remove the second sourcemap then you can properly inspect elements and have their styles resolve to the original *.less file.

As a workaround, you can pass the `{addComment: false}` option to gulp-sourcemaps (e.g., `sourcemaps.write({addComment: false})`) and it will nevertheless include the helpful first sourcemap, but not the problematic second one.

Sample html:

``` html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Source map</title>
    <link rel="stylesheet" href="double-sourcemaps.css">
</head>
<body>
    <p>Not being able to map styles to the original *.less file is unhelpful.</p>
</body>
</html>
```

Sample less:

``` css
body {
  font-family: 'Arial';
  font-size: 14px;
  margin: 14px;
}

p {
  margin: 14px 0;
}
```

Sample gulp task:

``` javascript
gulp.task('double-sourcemaps', function() {
    return gulp.src('app/double-sourcemaps.less')
        .pipe(sourcemaps.init())
        .pipe(less({compress: true}))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('app/'));
});
```

Resulting css file:

``` css
body{font-family:'Arial';font-size:14px;margin:14px}p{margin:14px 0}/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9ob21lL3BqL3Byb2plY3RzL2drYy91aS9hcHAvZG91YmxlLXNvdXJjZW1hcHMubGVzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxLQUNFLFlBQWEsT0FBYixDQUNBLGNBQUEsQ0FDQSxZQUdGLEVBQ0UifQ== */
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZG91YmxlLXNvdXJjZW1hcHMuY3NzIiwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsInNvdXJjZXMiOlsiZG91YmxlLXNvdXJjZW1hcHMubGVzcyJdLCJzb3VyY2VzQ29udGVudCI6WyJib2R5IHtcbiAgZm9udC1mYW1pbHk6ICdBcmlhbCc7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgbWFyZ2luOiAxNHB4O1xufVxuXG5wIHtcbiAgbWFyZ2luOiAxNHB4IDA7XG59XG4iXSwic291cmNlUm9vdCI6Ii9zb3VyY2UvIn0= */
```
